# Generated by Django 5.1.14 on 2025-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('published_date', models.CharField(blank=True, max_length=100)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
